//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.31 at 09:02:40 PM COT 
//


package com.leysoft.ws.autor;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.leysoft.ws.autor package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.leysoft.ws.autor
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllAutorResponse }
     * 
     */
    public GetAllAutorResponse createGetAllAutorResponse() {
        return new GetAllAutorResponse();
    }

    /**
     * Create an instance of {@link DeleteAutorRequest }
     * 
     */
    public DeleteAutorRequest createDeleteAutorRequest() {
        return new DeleteAutorRequest();
    }

    /**
     * Create an instance of {@link DeleteAutorResponse }
     * 
     */
    public DeleteAutorResponse createDeleteAutorResponse() {
        return new DeleteAutorResponse();
    }

    /**
     * Create an instance of {@link UpdateAutorRequest }
     * 
     */
    public UpdateAutorRequest createUpdateAutorRequest() {
        return new UpdateAutorRequest();
    }

    /**
     * Create an instance of {@link GetAllAutorRequest }
     * 
     */
    public GetAllAutorRequest createGetAllAutorRequest() {
        return new GetAllAutorRequest();
    }

    /**
     * Create an instance of {@link GetAutorRequest }
     * 
     */
    public GetAutorRequest createGetAutorRequest() {
        return new GetAutorRequest();
    }

    /**
     * Create an instance of {@link GetAutorResponse }
     * 
     */
    public GetAutorResponse createGetAutorResponse() {
        return new GetAutorResponse();
    }

    /**
     * Create an instance of {@link AddAutorResponse }
     * 
     */
    public AddAutorResponse createAddAutorResponse() {
        return new AddAutorResponse();
    }

    /**
     * Create an instance of {@link AddAutorRequest }
     * 
     */
    public AddAutorRequest createAddAutorRequest() {
        return new AddAutorRequest();
    }

    /**
     * Create an instance of {@link Autor }
     * 
     */
    public Autor createAutor() {
        return new Autor();
    }

    /**
     * Create an instance of {@link UpdateAutorResponse }
     * 
     */
    public UpdateAutorResponse createUpdateAutorResponse() {
        return new UpdateAutorResponse();
    }

}
