//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.31 at 09:02:40 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://leysoft.com/autor", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.leysoft.ws.autor;
